/**
 * pdfNest — PDF tool registry.
 * Single source of truth: routing, home grid, sitemap, search, SEO, favorites.
 * 26 LIVE tools + 12 SOON (comingSoon: true, no routes needed).
 */
import { FILE_LIMITS } from "./file-limits";
import type { Tool } from "@/lib/types/tools";

export const TOOLS: Tool[] = [
  // ── MANIPULATE ──────────────────────────────────────────────────────────────
  {
    id: "pdf-merge",
    name: "PDF Merge",
    slug: "pdf-merge",
    description: "Combine multiple PDF files into one document.",
    longDescription:
      "Merge two or more PDF files into a single document in seconds. Drag to reorder, then download your combined PDF — all processed locally in your browser.",
    category: "manipulate",
    icon: "Merge",
    features: [
      "Combine unlimited PDFs",
      "Drag to reorder files before merging",
      "Preserves original quality",
      "100% client-side — no upload",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    featured: true,
  },
  {
    id: "pdf-split",
    name: "PDF Split",
    slug: "pdf-split",
    description: "Split a PDF into individual pages or custom ranges.",
    longDescription:
      "Extract specific pages or split your PDF into separate files. Define page ranges or extract every page individually — all done in-browser.",
    category: "manipulate",
    icon: "Scissors",
    features: [
      "Split by page range",
      "Extract individual pages",
      "Download as separate files or ZIP",
      "No file size limit on output",
    ],
    maxFileSize: FILE_LIMITS.pdfMax.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    featured: true,
  },
  {
    id: "pdf-compress",
    name: "PDF Compress",
    slug: "pdf-compress",
    description: "Reduce PDF file size without losing quality.",
    longDescription:
      "Shrink your PDF file size for easier sharing and storage. Choose compression level and see the size reduction — processed entirely in your browser.",
    category: "manipulate",
    icon: "Archive",
    features: [
      "Multiple compression levels",
      "Preview before/after size",
      "Preserves text and images",
      "Up to 1 GB input",
    ],
    maxFileSize: FILE_LIMITS.pdfMax.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    featured: true,
  },
  {
    id: "pdf-rotate",
    name: "PDF Rotate",
    slug: "pdf-rotate",
    description: "Rotate PDF pages 90°, 180°, or 270°.",
    longDescription:
      "Fix the orientation of your PDF pages. Rotate all pages or select specific pages to rotate at 90°, 180°, or 270° — processed locally.",
    category: "manipulate",
    icon: "RotateCw",
    features: [
      "Rotate all or selected pages",
      "90°, 180°, 270° rotation",
      "Page thumbnail preview",
      "Instant download",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-reorder",
    name: "PDF Reorder",
    slug: "pdf-reorder",
    description: "Drag and drop to rearrange PDF pages.",
    longDescription:
      "Visually reorder the pages of your PDF by dragging thumbnails into the desired order. Quick, intuitive, and completely private.",
    category: "manipulate",
    icon: "ArrowUpDown",
    features: [
      "Visual drag-and-drop reordering",
      "Page thumbnail grid",
      "Undo reorder changes",
      "100% local processing",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-add-blank-pages",
    name: "PDF Add Blank Pages",
    slug: "pdf-add-blank-pages",
    description: "Insert blank pages into a PDF at any position.",
    longDescription:
      "Add blank pages to your PDF at the beginning, end, or between any pages. Useful for separators, notes space, or printing layouts.",
    category: "manipulate",
    icon: "FilePlus",
    features: [
      "Insert at any page position",
      "Add multiple blank pages at once",
      "Custom page size matching",
      "Instant preview",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-duplicate-pages",
    name: "PDF Duplicate Pages",
    slug: "pdf-duplicate-pages",
    description: "Duplicate specific pages within a PDF.",
    longDescription:
      "Create copies of specific pages inside your PDF. Great for templates, form repetition, or building multi-copy documents.",
    category: "manipulate",
    icon: "Copy",
    features: [
      "Duplicate any page multiple times",
      "Select specific pages to duplicate",
      "Insert duplicates at any position",
      "No quality loss",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-flatten",
    name: "PDF Flatten",
    slug: "pdf-flatten",
    description: "Flatten PDF form fields and annotations.",
    longDescription:
      "Merge form fields and annotations permanently into the PDF content. Useful before sharing or printing to prevent edits.",
    category: "manipulate",
    icon: "Layers",
    features: [
      "Flattens all AcroForm fields",
      "Removes interactive elements",
      "Ideal for final-share PDFs",
      "Preserves visual appearance",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-page-numbers",
    name: "PDF Page Numbers",
    slug: "pdf-page-numbers",
    description: "Add page numbers to a PDF document.",
    longDescription:
      "Automatically add page numbers to your PDF. Choose position, font size, start number, and format — all rendered client-side.",
    category: "manipulate",
    icon: "Hash",
    features: [
      "Customizable position (header/footer)",
      "Choose start page number",
      "Font size and color options",
      "Skip first page option",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-watermark",
    name: "PDF Watermark",
    slug: "pdf-watermark",
    description: "Add text or image watermark to PDF pages.",
    longDescription:
      "Protect or brand your PDF with a custom text watermark. Adjust opacity, angle, font size, and color — rendered client-side with pdf-lib.",
    category: "manipulate",
    icon: "Droplets",
    features: [
      "Custom text watermark",
      "Adjustable opacity and angle",
      "Apply to all or selected pages",
      "DOMPurify-sanitized text input",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    featured: true,
  },
  {
    id: "pdf-redact",
    name: "PDF Redact",
    slug: "pdf-redact",
    description: "Permanently black out sensitive text in a PDF.",
    longDescription:
      "Draw black boxes over sensitive content to permanently redact it. Pages are rasterized via PDF.js then rebuilt — the original text is gone.",
    category: "manipulate",
    icon: "EyeOff",
    features: [
      "Draw redaction boxes over any area",
      "Permanently removes hidden text",
      "Rasterize + rebuild for safety",
      "100% client-side",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },

  // ── SECURITY ────────────────────────────────────────────────────────────────
  {
    id: "pdf-password-protect",
    name: "PDF Password Protect",
    slug: "pdf-password-protect",
    description: "Protect a PDF with a password (stub — see note).",
    longDescription:
      "Note: Browser-side AES/RC4 PDF encryption is not yet possible with pdf-lib. This page explains the limitation and suggests alternatives.",
    category: "security",
    icon: "Lock",
    features: [
      "Honest explanation of browser limitation",
      "Links to desktop alternatives",
      "No server upload required",
      "Will be updated when browser APIs support it",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-unlock",
    name: "PDF Unlock",
    slug: "pdf-unlock",
    description: "Remove password protection from a PDF.",
    longDescription:
      "Unlock a password-protected PDF by providing the password. The file is re-saved without encryption — entirely in your browser.",
    category: "security",
    icon: "Unlock",
    features: [
      "Remove PDF password protection",
      "Enter password to decrypt",
      "Download clean unprotected PDF",
      "No server — fully private",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-sign",
    name: "PDF Sign",
    slug: "pdf-sign",
    description: "Draw or type a signature and add it to a PDF.",
    longDescription:
      "Electronically sign your PDF. Draw with your mouse/finger, or type your name in a signature font. Place the signature anywhere on any page.",
    category: "security",
    icon: "PenLine",
    features: [
      "Draw or type signature",
      "Place on any page and position",
      "Adjustable signature size",
      "Download signed PDF instantly",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    featured: true,
  },

  // ── FORMS & METADATA ────────────────────────────────────────────────────────
  {
    id: "pdf-form-filler",
    name: "PDF Form Filler",
    slug: "pdf-form-filler",
    description: "Fill AcroForm fields in a PDF document.",
    longDescription:
      "Detect and fill interactive AcroForm fields in your PDF. Text fields, checkboxes, dropdowns — all filled in your browser via pdf-lib.",
    category: "forms-metadata",
    icon: "FileEdit",
    features: [
      "Auto-detects AcroForm fields",
      "Fill text, checkbox, select fields",
      "Preview filled form",
      "Download filled PDF",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-metadata-editor",
    name: "PDF Metadata Editor",
    slug: "pdf-metadata-editor",
    description: "Edit title, author, subject, and keywords of a PDF.",
    longDescription:
      "View and edit the metadata stored in your PDF — title, author, subject, creator, and keywords. Save changes and download the updated file.",
    category: "forms-metadata",
    icon: "FileSearch",
    features: [
      "Edit title, author, subject, creator",
      "Add/remove keywords",
      "Preview metadata before saving",
      "Clean metadata option",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-metadata-viewer",
    name: "PDF Metadata Viewer",
    slug: "pdf-metadata-viewer",
    description: "View all metadata stored in a PDF file.",
    longDescription:
      "Inspect all metadata embedded in your PDF — title, author, creation date, modification date, PDF version, and more. No download needed.",
    category: "forms-metadata",
    icon: "Info",
    features: [
      "View all standard PDF metadata",
      "Shows creation and modification dates",
      "Displays PDF version",
      "No file download — read-only",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },

  // ── PDF TO OTHER ────────────────────────────────────────────────────────────
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    slug: "pdf-to-jpg",
    description: "Convert each PDF page to a high-quality JPG image.",
    longDescription:
      "Render every page of your PDF to a JPEG image. Choose DPI and quality, then download individual images or a ZIP archive — all via PDF.js.",
    category: "pdf-to-other",
    icon: "ImageDown",
    features: [
      "Render each page as JPEG",
      "Adjustable DPI and quality",
      "Download individually or as ZIP",
      "High-resolution output",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    featured: true,
  },
  {
    id: "pdf-to-png",
    name: "PDF to PNG",
    slug: "pdf-to-png",
    description: "Convert each PDF page to a lossless PNG image.",
    longDescription:
      "Render every page of your PDF to a PNG image with transparent background support. Choose DPI, then download individually or as ZIP.",
    category: "pdf-to-other",
    icon: "FileImage",
    features: [
      "Lossless PNG output",
      "Transparent background support",
      "Adjustable DPI",
      "Download individually or as ZIP",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-to-text",
    name: "PDF to Text",
    slug: "pdf-to-text",
    description: "Extract all text content from a PDF document.",
    longDescription:
      "Extract plain text from every page of your PDF using PDF.js text extraction. Copy to clipboard or download as a .txt file.",
    category: "pdf-to-other",
    icon: "FileText",
    features: [
      "Extract text from all pages",
      "Preserves paragraph structure",
      "Copy to clipboard or download",
      "Works with searchable PDFs",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    slug: "pdf-to-word",
    description: "Convert a PDF to an editable Word document (.docx).",
    longDescription:
      "Extract text from your PDF using PDF.js, then build a .docx file with proper paragraphs. Best for text-heavy, searchable PDFs.",
    category: "pdf-to-other",
    icon: "FileCode",
    features: [
      "Extracts text via PDF.js",
      "Builds real .docx with paragraphs",
      "Page-break aware",
      "Best for text-based PDFs",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    featured: true,
  },
  {
    id: "pdf-extract-images",
    name: "PDF Extract Images",
    slug: "pdf-extract-images",
    description: "Extract all embedded images from a PDF.",
    longDescription:
      "Pull every embedded image out of your PDF and download them as a ZIP archive. Powered by PDF.js image extraction — 100% client-side.",
    category: "pdf-to-other",
    icon: "Images",
    features: [
      "Extract all embedded images",
      "Download as ZIP archive",
      "Supports JPEG and PNG images",
      "No quality loss on extraction",
    ],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
  },

  // ── OTHER TO PDF ────────────────────────────────────────────────────────────
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    slug: "image-to-pdf",
    description: "Convert one or more images into a single PDF.",
    longDescription:
      "Turn JPEG, PNG, or WebP images into a PDF document. Upload multiple images and they become individual pages — generated by jsPDF in your browser.",
    category: "other-to-pdf",
    icon: "FileImage",
    features: [
      "Supports JPEG, PNG, WebP",
      "Multiple images → one PDF",
      "Auto-fit to page",
      "Preserve image aspect ratio",
    ],
    maxFileSize: FILE_LIMITS.image.maxSize,
    acceptedTypes: [...FILE_LIMITS.image.acceptedTypes],
    featured: true,
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    slug: "html-to-pdf",
    description: "Convert an HTML page or snippet to a PDF document.",
    longDescription:
      "Paste HTML or upload an HTML file and convert it to PDF using html2pdf.js. Renders in a sandboxed iframe — all in-browser, no server needed.",
    category: "other-to-pdf",
    icon: "Globe",
    features: [
      "Paste HTML or upload .html file",
      "Renders via html2canvas + jsPDF",
      "Supports CSS styles",
      "Download as PDF instantly",
    ],
    maxFileSize: FILE_LIMITS.text.maxSize,
    acceptedTypes: ["text/html"],
  },
  {
    id: "markdown-to-pdf",
    name: "Markdown to PDF",
    slug: "markdown-to-pdf",
    description: "Convert Markdown text to a formatted PDF document.",
    longDescription:
      "Write or paste Markdown and export it as a styled PDF. Uses marked.js for parsing + DOMPurify for safety + html2pdf.js for rendering.",
    category: "other-to-pdf",
    icon: "FileCode",
    features: [
      "Full Markdown support",
      "DOMPurify-sanitized HTML",
      "Styled output with headers/code blocks",
      "Download or copy rendered HTML",
    ],
    maxFileSize: FILE_LIMITS.text.maxSize,
    acceptedTypes: ["text/plain", "text/markdown"],
  },
  {
    id: "text-to-pdf",
    name: "Text to PDF",
    slug: "text-to-pdf",
    description: "Convert plain text to a PDF document.",
    longDescription:
      "Type or paste plain text and download it as a properly formatted PDF. Supports font size, line spacing, and margin customization via jsPDF.",
    category: "other-to-pdf",
    icon: "Type",
    features: [
      "Type or paste any text",
      "Adjustable font size and margins",
      "Auto page breaks",
      "Download as PDF instantly",
    ],
    maxFileSize: FILE_LIMITS.text.maxSize,
    acceptedTypes: ["text/plain"],
  },

  // ── SOON (comingSoon: true — no routes required) ────────────────────────────
  {
    id: "pdf-delete-pages",
    name: "PDF Delete Pages",
    slug: "pdf-delete-pages",
    description: "Remove unwanted pages from a PDF.",
    longDescription: "Select and permanently delete pages from your PDF document.",
    category: "manipulate",
    icon: "Trash2",
    features: ["Select pages to delete", "Preview before deleting", "Download cleaned PDF"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
  {
    id: "pdf-extract-pages",
    name: "PDF Extract Pages",
    slug: "pdf-extract-pages",
    description: "Extract specific pages into a new PDF.",
    longDescription: "Pull out specific pages from your PDF and save them as a separate document.",
    category: "manipulate",
    icon: "FileOutput",
    features: ["Extract page ranges", "Select non-contiguous pages", "Download extracted PDF"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
  {
    id: "pdf-organize",
    name: "PDF Organize",
    slug: "pdf-organize",
    description: "Full drag-and-drop PDF page organizer.",
    longDescription: "Reorder, delete, rotate and duplicate pages in one visual editor.",
    category: "manipulate",
    icon: "LayoutGrid",
    features: ["Combined reorder, delete, rotate", "Visual thumbnail grid", "Multi-select pages"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
  {
    id: "pdf-crop",
    name: "PDF Crop",
    slug: "pdf-crop",
    description: "Crop the margins and content area of PDF pages.",
    longDescription: "Define a crop box to trim margins or focus on specific content areas.",
    category: "manipulate",
    icon: "Crop",
    features: ["Visual crop area selection", "Apply to all or selected pages", "Preserve original"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
  {
    id: "pdf-n-up",
    name: "PDF N-up",
    slug: "pdf-n-up",
    description: "Print multiple PDF pages on a single sheet.",
    longDescription: "Place 2, 4, 6, or 9 pages on a single printed sheet to save paper.",
    category: "manipulate",
    icon: "Grid2x2",
    features: ["2-up, 4-up, 6-up, 9-up layouts", "Portrait and landscape", "Adjustable margins"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
  {
    id: "pdf-booklet",
    name: "PDF Booklet",
    slug: "pdf-booklet",
    description: "Convert a PDF for saddle-stitch booklet printing.",
    longDescription: "Reorder pages for folded booklet printing — fold the output and staple it.",
    category: "manipulate",
    icon: "BookOpen",
    features: ["Saddle-stitch imposition", "Auto page ordering", "Print-ready output"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
  {
    id: "pdf-grayscale",
    name: "PDF Grayscale",
    slug: "pdf-grayscale",
    description: "Convert a color PDF to grayscale.",
    longDescription: "Render all pages to grayscale using PDF.js — useful before black-and-white printing.",
    category: "manipulate",
    icon: "SunMoon",
    features: ["Convert all pages to grayscale", "Smaller file size output", "Preserve text sharpness"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
  {
    id: "pdf-header-footer",
    name: "PDF Header & Footer",
    slug: "pdf-header-footer",
    description: "Add custom header and footer text to a PDF.",
    longDescription: "Stamp custom header and footer text on every page — dates, titles, or custom strings.",
    category: "manipulate",
    icon: "AlignCenter",
    features: ["Custom header and footer text", "Position: left/center/right", "Include page numbers"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
  {
    id: "pdf-bates-numbering",
    name: "PDF Bates Numbering",
    slug: "pdf-bates-numbering",
    description: "Apply Bates numbering to legal or archival PDFs.",
    longDescription: "Stamp sequential Bates numbers with custom prefix and padding on each page.",
    category: "manipulate",
    icon: "ListOrdered",
    features: ["Custom prefix and suffix", "Configurable padding", "Start number and position"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
  {
    id: "pdf-repair",
    name: "PDF Repair",
    slug: "pdf-repair",
    description: "Attempt to repair a damaged or malformed PDF.",
    longDescription: "Load a damaged PDF through pdf-lib's recovery mode to salvage readable content.",
    category: "manipulate",
    icon: "Wrench",
    features: ["Load with recovery mode", "Re-save clean structure", "Works on partially-corrupt files"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
  {
    id: "pdf-compare",
    name: "PDF Compare",
    slug: "pdf-compare",
    description: "Compare two PDF documents side-by-side.",
    longDescription: "Render two PDFs side-by-side to visually compare content differences page by page.",
    category: "pdf-to-other",
    icon: "ArrowLeftRight",
    features: ["Side-by-side page view", "Page-level navigation", "Highlight differences"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
  {
    id: "pdf-to-csv",
    name: "PDF to CSV/Excel",
    slug: "pdf-to-csv",
    description: "Extract tables from a PDF and export to CSV.",
    longDescription: "Detect and extract table data from PDFs using PDF.js text extraction and export as CSV.",
    category: "pdf-to-other",
    icon: "Table",
    features: ["Table detection from PDF", "Export as CSV", "Multiple table support"],
    maxFileSize: FILE_LIMITS.pdf.maxSize,
    acceptedTypes: [...FILE_LIMITS.pdf.acceptedTypes],
    comingSoon: true,
  },
];

/** Live tools (no comingSoon) */
export const LIVE_TOOLS = TOOLS.filter((t) => !t.comingSoon);

/** Soon tools */
export const SOON_TOOLS = TOOLS.filter((t) => t.comingSoon);

/** Featured live tools */
export const FEATURED_TOOLS = TOOLS.filter((t) => !t.comingSoon && t.featured);

/** Tool map for O(1) lookup by slug */
export const TOOL_MAP = new Map(TOOLS.map((t) => [t.slug, t]));

/** Category label map */
export const CATEGORY_LABELS: Record<string, string> = {
  manipulate: "Manipulate",
  security: "Security",
  "forms-metadata": "Forms & Metadata",
  "pdf-to-other": "PDF to Other",
  "other-to-pdf": "Other to PDF",
};

export const CATEGORIES = [
  "manipulate",
  "security",
  "forms-metadata",
  "pdf-to-other",
  "other-to-pdf",
] as const;
