export const siteConfig = {
  name: "pdfNest",
  tagline: "Your PDFs never leave your device.",
  description:
    "Free online PDF tools — merge, split, compress, convert, sign, and more. 100% browser-based, no upload, no sign-up. Your PDFs never leave your device.",
  url: process.env.NEXT_PUBLIC_APP_URL ?? "https://pdfnest.app",
  ogImage: `${process.env.NEXT_PUBLIC_APP_URL ?? "https://pdfnest.app"}/og/default.png`,
  creator: "pdfNest",
  keywords: [
    "free pdf tools online",
    "pdf nest",
    "pdf merge free",
    "pdf split online",
    "pdf compress online",
    "pdf to jpg converter",
    "image to pdf converter",
    "pdf sign online free",
    "pdf watermark",
    "pdf metadata editor",
    "merge pdf files free",
    "compress pdf file",
    "pdf to word converter free",
    "browser based pdf tools",
    "no upload pdf tools",
    "privacy first pdf",
    "client side pdf processing",
    "free online pdf converter",
  ],
} as const;
